plugins:
  discourse_api_key:
    default: ''
    client: false
    hidden: false

  discourse_base_url:
    default: https://some-url.com
    client: false
    hidden: false

  mailgun_api_key:
    default: ''
    regex: '^((key-)?\h{32}|\h{32}-\h{8}-\h{8})$'
    secret: true
    client: false

  discourse_api_username:
    default: api_username
    client: false
    hidden: false
