plugins:
  mailgun_api_key:
    default: ''
    client: false
    hidden: false

  discourse_base_url:
    default: https://some-url.com
    client: false
    hidden: false

  discourse_api_key:
    default: some-api-key
    client: false
    hidden: false

  discourse_api_username:
    default: api_username
    client: false
    hidden: false
